# Generated by Django 4.1.3 on 2022-11-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField(blank=True, null=True)),
                ('surface', models.IntegerField(blank=True, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
