version: '3.7'

services:
  report_openreal:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/report_openreal
    ports:
      - "8000:8000"