version: '3.7'

services:
  report_openreal:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/report_openreal
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  # message_queue:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: python consumer.py
    # deploy:
    #   resources:
    #     limits:
    #       memory: 5gb